apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: mongo
spec:
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
